# Generated by Django 2.0.5 on 2018-06-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=256)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('n', 'Not Started'), ('o', 'Ongoing'), ('p', 'Paused'), ('c', 'Complete')], default='n', help_text='Reading status', max_length=1)),
            ],
            options={
                'ordering': ['last_viewed'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category name', max_length=200)),
                ('subdirs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives_app.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives_app.Category'),
        ),
    ]
