# Generated by Django 2.0.5 on 2018-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(default='', help_text='Enter the path of file on local system.', max_length=256),
            preserve_default=False,
        ),
    ]
