# Generated by Django 2.0.5 on 2018-06-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0002_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='path',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a category name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(help_text='Enter the path of file on local system.', max_length=256, unique=True),
        ),
    ]
