# Generated by Django 2.0.5 on 2018-06-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives_app', '0003_auto_20180606_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subdirs',
            new_name='parent',
        ),
    ]
